### ISSUE TITLE
cannot install the bundle

### ISSUE THREAD

**Issue by OskarStark** [indigophp/sonata-admin-print-bundle#1]
[InvalidArgumentException]
  Could not find package indigophp/sonata-admin-print-bundle at any version for your minimum-stability (stable). Check the package spelling or your minimum
  -stability

**Comment by sagikazarmark** [comment]
Since there is no stable release of this package, this is the expected behavior :smile: 

Set minimum-stability to dev (and/or add `@dev` to the version cosntraint)

**Comment by OskarStark** [comment]
Thank you :+1:
